name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: true
  NG_CLI_ANALYTICS: 'false'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Update npm CLI
        run: npm install --global npm@latest

      - name: Install
        run: npm ci

      - name: Verify repository
        run: npm run check
